#!/bin/bash

export ARANGODB_ROOT="/Applications/ArangoDB.app/Contents/MacOS/"
export DATABASEDIR="${ARANGODB_ROOT}opt/arangodb/var/lib/arangodb"
export LOGDIR="${ARANGODB_ROOT}opt/arangodb/var/log/arangodb"
export PKGDATADIR="${ARANGODB_ROOT}opt/arangodb/share/arangodb"

exec "${ARANGODB_ROOT}opt/arangodb/bin/arangorestore" -c "${ARANGODB_ROOT}opt/arangodb/etc/arangodb/arangorestore-relative.conf" $*
